import { hasVariants, resolveVariant, storefrontPrice, isDemoPrice, canBuy } from './variants.js';

export function accessoryDetail(product, helpers) {
  const { crumbs, imageBlock, escape, icon, favorites, catalogProducts, card, money, variantId, quantity = 1 } = helpers;
  const p = resolveVariant(product, variantId);
  if (!p) return '';
  const price = storefrontPrice(p);
  const demo = isDemoPrice(p);
  const variants = hasVariants(product) && product.variants.length > 1;
  const sku = p.manufacturerSku || p.model || p.supplier?.sku;
  const label = product.optionLabel || p.optionLabel || 'Вариант';
  const source = (title,name,url) => url ? `<p><a class="text-link" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(title)} - ${escape(name || '')}</a></p>` : '';
  const availability = { pending:'Наличие уточняется', available:'Наличие указано в каталоге источника', 'in-stock':'Наличие указано в каталоге источника', unavailable:'Этот вариант сейчас недоступен', 'out-of-stock':'Этот вариант сейчас недоступен', outOfStock:'Этот вариант сейчас недоступен', discontinued:'Этот вариант снят с продажи' }[p.availabilityStatus] || 'Наличие уточняется';
  return `<div class="page">${crumbs(product.name)}<div class="detail-grid">${imageBlock(p.image,'detail-image')}<div class="detail-copy"><span class="eyebrow">${escape(p.line || p.brand || '')}</span><h1>${escape(p.name || product.name)}</h1>${variants?`<p class="variant-current">${escape(label)}: ${escape(p.label)}</p>`:''}<div class="detail-price">${money(price)}</div><p class="retail-note">${demo?'Демонстрационная цена':p.retailPrice?.type==='recommended'?'Рекомендованная розничная цена':'Временная розничная цена'}${!demo&&p.packageWeightKg?` · ${money(price/p.packageWeightKg)} / кг`:''}<br>${escape(availability)}</p><p>${escape(p.description || '')}</p><span class="size-label">${escape(label)}</span><div class="size-options variant-options" aria-label="${escape(label)}">${variants?product.variants.map(v=>`<button class="size ${v.id===p.id?'active':''}" data-variant="${escape(v.id)}" aria-pressed="${v.id===p.id}">${escape(v.label)}</button>`).join(''):(p.sizes || []).map(s=>`<span class="size active">${escape(s)}</span>`).join('')}</div><div class="buy-row">${canBuy(p)?`<div class="quantity"><button data-detail-qty="-1" aria-label="Уменьшить количество">${icon('minus')}</button><span id="detail-qty">${quantity}</span><button data-detail-qty="1" aria-label="Увеличить количество">${icon('plus')}</button></div>`:''}<button class="button" ${canBuy(p)?`data-buy="${escape(product.id)}"`:'disabled'}>${canBuy(p)?'Добавить в корзину':'Вариант недоступен'} ${canBuy(p)?icon('bag'):''}</button><button class="icon-button favorite-detail ${favorites.includes(product.id)?'selected':''}" data-favorite="${escape(product.id)}" aria-label="В избранное" aria-pressed="${favorites.includes(product.id)}">${icon('heart')}</button></div><details open><summary>${p.category==='Корм'?'О корме':'О товаре'}</summary><ul>${(p.details || []).map(d=>`<li>${escape(d)}</li>`).join('')}</ul></details><details open><summary>Информация о товаре</summary><p>Бренд: ${escape(p.brand || '')}${sku?`<br>Артикул: ${escape(sku)}`:''}${p.supplier?.sku?`<br>Артикул поставщика: ${escape(p.supplier.sku)}`:''}${p.ean?`<br>EAN: ${escape(p.ean)}`:''}${p.weight?`<br>Упаковка: ${escape(p.weight)}`:''}<br>${escape(availability)}</p>${source('Карточка поставщика',p.supplier?.name,p.supplier?.url)}${source(p.productSource?.kind==='supplier'?'Источник товара':'Описание производителя',p.productSource?.name,p.productSource?.url)}${source('Источник фото',p.imageSource?.name,p.imageSource?.pageUrl)}${source(demo?'Источник информации о цене':'Розничный ориентир',p.retailPrice?.sourceName,p.retailPrice?.sourceUrl)}</details></div></div></div><section class="section"><div class="section-head"><h2>Хорошо вместе</h2><a class="text-link" href="#/catalog">Все товары</a></div><div class="product-grid">${catalogProducts.filter(x=>x.id!==product.id&&x.category===product.category).slice(0,4).map(card).join('')}</div></section>`;
}
